### ISSUE TITLE
Potential Missing Transpose

### ISSUE THREAD

**Issue by cvarchb** [DRezeanu/ColorOpponentModel#1]
Hi, 
In the 'Calculate Gain Coefficients for Environmental White' section of ColorOpponentModel.mlx, whenever I switch the illuminant from EE to either of the others, the gains calculated by lsqnonlin go to zero, causing the curves of the Cone Opponent Mechanisms to flatline. It seems like adding a transpose to the spectrum (for example changing from *d65spectrum to *d65spectrum' ) fixes the issue. This might need revising in your upload unless I unknowingly modified the code on my end.
Thanks,
Ben

**Comment by DRezeanu** [comment]
Resolved, thanks for pointing this out! 

-Dragos
